// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  ClearTurnsTurnsDeleteData,
  ClearTurnsTurnsDeleteResponses,
  CreateTurnTurnsPostData,
  CreateTurnTurnsPostErrors,
  CreateTurnTurnsPostResponses,
  DeleteTurnTurnsTurnIdDeleteData,
  DeleteTurnTurnsTurnIdDeleteErrors,
  DeleteTurnTurnsTurnIdDeleteResponses,
  GetTurnsTurnsGetData,
  GetTurnsTurnsGetResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  ReadRootGetData,
  ReadRootGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Clear Turns
 * Clear all turns
 */
export const clearTurnsTurnsDelete = <ThrowOnError extends boolean = false>(
  options?: Options<ClearTurnsTurnsDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ClearTurnsTurnsDeleteResponses,
    unknown,
    ThrowOnError
  >({
    url: "/turns/",
    ...options,
  });
};

/**
 * Get Turns
 * Get all turns
 */
export const getTurnsTurnsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTurnsTurnsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetTurnsTurnsGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/turns/",
    ...options,
  });
};

/**
 * Create Turn
 * Create a new turn
 */
export const createTurnTurnsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTurnTurnsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateTurnTurnsPostResponses,
    CreateTurnTurnsPostErrors,
    ThrowOnError
  >({
    url: "/turns/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Turn
 * Delete a turn by ID
 */
export const deleteTurnTurnsTurnIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTurnTurnsTurnIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteTurnTurnsTurnIdDeleteResponses,
    DeleteTurnTurnsTurnIdDeleteErrors,
    ThrowOnError
  >({
    url: "/turns/{turn_id}",
    ...options,
  });
};

/**
 * Read Root
 * Root endpoint
 */
export const readRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadRootGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadRootGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/",
    ...options,
  });
};

/**
 * Health Check
 * Health check endpoint
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/health",
    ...options,
  });
};
