// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetCharacterCharactersCharacterIdGetData,
  GetCharacterCharactersCharacterIdGetErrors,
  GetCharacterCharactersCharacterIdGetResponses,
  GetCharactersCharactersGetData,
  GetCharactersCharactersGetResponses,
  GetData,
  GetMonsterMonstersMonsterIdGetData,
  GetMonsterMonstersMonsterIdGetErrors,
  GetMonsterMonstersMonsterIdGetResponses,
  GetMonstersMonstersGetData,
  GetMonstersMonstersGetResponses,
  GetResponses,
  GetScenarioScenariosScenarioIdGetData,
  GetScenarioScenariosScenarioIdGetErrors,
  GetScenarioScenariosScenarioIdGetResponses,
  GetScenariosScenariosGetData,
  GetScenariosScenariosGetResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 *
 * Root endpoint
 */
export const get = <ThrowOnError extends boolean = false>(
  options?: Options<GetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });
};

/**
 * Health Check
 * Health check endpoint
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/health",
    ...options,
  });
};

/**
 * Get Characters
 * Get all available characters
 */
export const getCharactersCharactersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetCharactersCharactersGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCharactersCharactersGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/characters/",
    ...options,
  });
};

/**
 * Get Character
 * Get a specific character by ID
 */
export const getCharacterCharactersCharacterIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCharacterCharactersCharacterIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetCharacterCharactersCharacterIdGetResponses,
    GetCharacterCharactersCharacterIdGetErrors,
    ThrowOnError
  >({
    url: "/characters/{character_id}",
    ...options,
  });
};

/**
 * Get Monsters
 * Get all available monsters
 */
export const getMonstersMonstersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMonstersMonstersGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetMonstersMonstersGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/monsters/",
    ...options,
  });
};

/**
 * Get Monster
 * Get a specific monster by ID
 */
export const getMonsterMonstersMonsterIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetMonsterMonstersMonsterIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetMonsterMonstersMonsterIdGetResponses,
    GetMonsterMonstersMonsterIdGetErrors,
    ThrowOnError
  >({
    url: "/monsters/{monster_id}",
    ...options,
  });
};

/**
 * Get Scenarios
 * Get all available scenarios
 */
export const getScenariosScenariosGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetScenariosScenariosGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetScenariosScenariosGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/scenarios/",
    ...options,
  });
};

/**
 * Get Scenario
 * Get a specific scenario by ID
 */
export const getScenarioScenariosScenarioIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetScenarioScenariosScenarioIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetScenarioScenariosScenarioIdGetResponses,
    GetScenarioScenariosScenarioIdGetErrors,
    ThrowOnError
  >({
    url: "/scenarios/{scenario_id}",
    ...options,
  });
};
