// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Turn
 */
export type Turn = {
  /**
   * Id
   */
  id?: number | null;
  /**
   * Player
   */
  player: string;
  /**
   * Action
   */
  action: string;
  /**
   * Initiative
   */
  initiative: number;
};

/**
 * TurnResponse
 */
export type TurnResponse = {
  /**
   * Message
   */
  message: string;
  turn: Turn;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type ClearTurnsTurnsDeleteData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/turns/";
};

export type ClearTurnsTurnsDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetTurnsTurnsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/turns/";
};

export type GetTurnsTurnsGetResponses = {
  /**
   * Response Get Turns Turns  Get
   * Successful Response
   */
  200: Array<Turn>;
};

export type GetTurnsTurnsGetResponse =
  GetTurnsTurnsGetResponses[keyof GetTurnsTurnsGetResponses];

export type CreateTurnTurnsPostData = {
  body: Turn;
  path?: never;
  query?: never;
  url: "/turns/";
};

export type CreateTurnTurnsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTurnTurnsPostError =
  CreateTurnTurnsPostErrors[keyof CreateTurnTurnsPostErrors];

export type CreateTurnTurnsPostResponses = {
  /**
   * Successful Response
   */
  200: TurnResponse;
};

export type CreateTurnTurnsPostResponse =
  CreateTurnTurnsPostResponses[keyof CreateTurnTurnsPostResponses];

export type DeleteTurnTurnsTurnIdDeleteData = {
  body?: never;
  path: {
    /**
     * Turn Id
     */
    turn_id: number;
  };
  query?: never;
  url: "/turns/{turn_id}";
};

export type DeleteTurnTurnsTurnIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTurnTurnsTurnIdDeleteError =
  DeleteTurnTurnsTurnIdDeleteErrors[keyof DeleteTurnTurnsTurnIdDeleteErrors];

export type DeleteTurnTurnsTurnIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadRootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type ReadRootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
